version: "3"
services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    #volumes:
     # - ./mysql/data:/var/lib/mysql
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_USER: visitor
      MYSQL_PASSWORD: visitor
      MYSQL_DATABASE: myDB
      MYSQL_ROOT_PASSWORD: root
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    environment:
      - ENV=develop


  backend:
    build: ./backend
    expose:
      - "8000"
    ports:
      - 80:8000
    restart: always
    depends_on:
      - mysql
      - redis
  DBadmin:
    image: adminer
    ports:
      - 7980:8080
  # proxy:
  #   image: nginx:stable-alpine
  #   restart: always
  #   ports:
  #     - 8080:80
  #   volumes:
  #     - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #   depends_on:
  #     - backend
